### ISSUE TITLE
Make it work with linked poselibs

### ISSUE THREAD

**Issue by jasperges** [jasperges/pose-thumbnails#28]
All props are now stored on the Pose Library (Action). When that is linked you can't change these, so you can't even change a pose with the thumbnails. Probably have to add some/most props to the armature that can be 'proxified' and then it should work.

**Comment by TheDuckCow** [comment]
One idea might be, instead of linking the actions, have the addon auto remove/re-append at any typical time that libraries are re-loaded (file open). This would allow them to modify and use it normally as if local, the only exception being there's a false sense that new poses or changes to defaults would be saved to the "master" library. I have some thoughts on how even that would be possible though.

**Comment by jasperges** [comment]
@TheDuckCow Could you open a new issue and elaborate a bit more about what you have in mind? The addon now properly works with linked armatures and pose libraries the 'Blender way'. But I'm open to suggestions to add other (improved) functionality.

Closing this now, because the original issue should be fixed.
