### ISSUE TITLE
Suggestions for improving usability of library enum dropdown

### ISSUE THREAD

**Issue by TheDuckCow** [jasperges/pose-thumbnails#51]
Having just had some trouble to make the pose library enum dropdown to work with actions I had setup (and having needed to jump into the code to see how it was actually working), I have a couple minor suggestions:

- Either make the default setting for `pose_lib_name_prefix` be `PLB_`, OR update the comment tip for the `pose_lib_for_char` enum to match the default setting, ie `Only lists Pose Libraries for the current character, i.e. PLB-{charname}*` as that took me some time to figure out why it wasn't populating (tooltip said use _ but default setting actually uses -)
- Alt suggestion: Do away with the dashes or whatever for the prefix, and add some default segmentation characters to the regex (e.g. `{1}[-_. ]`) so that as long as the prefix of the entire action matches the character letters of the preferences prefix, it should work without trying to remember if it should be a dash or a space etc.
  - I realize there's coded logic for making something like char_blenrig be treated as unique from char-blendrig which would resolve to char, so this logic of the separator could just be used in the context of the very first separator for the purposes of what to draw in the enum items list of pose libraries
  - Further motivation - there's not *that* much harm in showing maybe more items than you want in that enum, but there is if it's hard to get the enum to draw anything at all due to mismatches
- Consider adding a little more help text to the enum tooltip, something perhaps like: `Only lists Pose Libraries for the current character, i.e. PLB-{charname}*, based on selected armature object name` since the armature object name (not the group, not the armature datablock) is the other relevant thing. 
- Maybe another user-centric thing to do is create an operator, like the sanitize button, but for the action name to make it populate correctly in the enum dropdown.
  - Pressing this would auto prefix the PLB (or whatever from user prefs) and pull in the characters name based off of the rig, that way they don't have to fiddle around with getting the right name just to make the action appear in the library enum dropdown.
- [Added after initial post] Also expand the rules about how the rig is named such that {charactername}_proxy is also recognized, as when linking into another scene and then proxying, the rig proxy is given this name. Right now the workaround is to rename the proxy rig by chopping off the _proxy part. 

If you like some or any of these ideas, I'm happy to slap the code together and make a pull request. I think at the very least the first and last two would be good to do, but that's just me.

**Comment by jasperges** [comment]
What you say makes perfect sense to me. The only remark I have is about the second point: make sure the matching is not too greedy. I agree it can be frustrating or confusing for 'less technical' users if things don't show up. But it can also be fairly annoying if you set everything up concisely and too much shows up.
If you can make a pull request, that would be great.

Another thing: personally I don't use the add-on at all and due to my current work I don't have time to work on it. So after your pull request I will probably (finally!) make an official 1.0 release.
After that, if you would like to make further improvements or add features, please go ahead. It might be a good idea to also discuss things with @sybrenstuvel, because he did all the latest updates and they are using it at the Blender Studio. Mainly to keep it 1 add-on and not split it into several forks. If you or somebody else would like to take 'ownership' of the add-on, that is also perfectly fine with me. But I don't mind having the 'official' version here, merging pull requests and creating a new release once in a while.

Hopefully in the future this add-on is not needed any more, because similar functionality is then implemented in Blender itself.

**Comment by TheDuckCow** [comment]
Thanks for the reply @jasperges, and I agree with your number 2 comments - I think the text overlay update with be sufficient there, so I won't do that.

@sybrenstuvel couple questions to you if you get the chance:
1) Is the branch on your account to be treated as more up to date?
2) Do you have anything against the proposed changes noted in 1), 4), and 5) above?
3) Are there any such near-term plans for this or equivalent (visual pose lib) becoming a default Blender addon?

**Comment by sybrenstuvel** [comment]
> Is the branch on your account to be treated as more up to date?

Well, it's where I do my development for the Blender Animation Studio. Whether it is more up to date depends on what both me and Jasper are doing at any particular time. The past months, yes, it's been more up to date, at least until I sent another pull request to Jasper.

> Do you have anything against the proposed changes noted in 1), 4), and 5) above?

I think 1, 3, and 4 are all good points.

Number 5 would be a rather personal thing; in the studio we never keep the _proxy suffix, so we don't need this feature. Since the match is done with a regular expression, you can already alter this to your needs.

> Are there any such near-term plans for this or equivalent (visual pose lib) becoming a default Blender addon?

There is the wish to get this in there, but nothing is planned short-term.

**Comment by TheDuckCow** [comment]
PR submitted here (https://github.com/jasperges/pose-thumbnails/pull/52), which implements 1, 3, and 4 above. 

Happy to take any edit feedback from either of you @jasperges and @sybrenstuvel, as well as happy to make a similar PR to the 2.8 branch for just this commit's changes (https://github.com/TheDuckCow/pose-thumbnails/commit/cedcbdfec7c9ccb88e055ef9c24e5ec528664231)

**Comment by TheDuckCow** [comment]
Merged, closing the issue.
