### ISSUE TITLE
Last versions of blender 2.8 doesn't work

### ISSUE THREAD

**Issue by brehiner** [jasperges/pose-thumbnails#55]
The las version who work was of 25 of december of 2018

**Comment by jasperges** [comment]
You mean the blender-2.8 branch? That is correct. This hasn't been updated in a while.
At some point it should also be updated, but I don't have time for it at the moment.

**Comment by sebababi** [comment]
Hello Jasperges,
I suppose this is your addon, I see a fork to your here: github.com/sybrenstuvel/pose_thumbnails
I assume a "fork" is like a link.
I hope you can find some time to migrate it to 2.8, it's such a good addon, 
as they say: A Picture is Worth a Thousand Words 
;o)

**Comment by jasperges** [comment]
Hi @sebababi,

A fork is basically a new project, based on an existing one. They might end up totally different, but in this case it's mainly to make it work in Blender 2.80. The fork by Sybren/Blender Institute is now officially hosted here, by the way: https://gitlab.com/blender-institute/pose-thumbnails
At the moment if you need this add-on to work in Blender 2.80, just use the fork. In the future I hope to 'officially' support Blender 2.80, but I just don't have time to work on the add-on at the moment.

**Comment by sebababi** [comment]
Great Jaspes

Thanks a lot I really appreciate,

It¹s such a good and important addon,

Sebastian

**Comment by TheDuckCow** [comment]
@jasperges are you looking to merge in changes / just fully support 2.8 and drop 2.7, or are you looking to update the addon so it works for both?

My own 2c: I'd argue for supporting both at once, even if it calls for some non-best addon practices in some sense (happy to help). Or, leave this repo as-is so that people at least have a clear option to use still for 2.7x, while 2.8 users can use the institute's version.
